name: SwiftSync
description: "Developed by Abdul Sami Abbasi"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  connectivity_plus: ^7.1.1
  image_picker: ^1.2.2
  firebase_storage: ^13.3.0
  http: ^1.2.2
  firebase_messaging: 16.2.0
  flutter_local_notifications: ^18.0.1
  dart_jsonwebtoken: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "transparent"  # ← add this
  adaptive_icon_foreground: "assets/images/app_logo.png"  # ← add this


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/service_account.json    # ← FCM service account credentials