// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1wSPjqxyLngjXHT_-eRbeWEhyV_6gck',
    appId: '1:778448751554:web:0431f34f8a9e7fd821e45b',
    messagingSenderId: '778448751554',
    projectId: 'swift-sync-by-abdulsami',
    authDomain: 'swift-sync-by-abdulsami.firebaseapp.com',
    storageBucket: 'swift-sync-by-abdulsami.firebasestorage.app',
    measurementId: 'G-ZEHE4G1XBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtPq-Y46fGUZEjcg_COHt1s6Q6z6ChpM',
    appId: '1:778448751554:android:b0c35e1a6df8db9e21e45b',
    messagingSenderId: '778448751554',
    projectId: 'swift-sync-by-abdulsami',
    storageBucket: 'swift-sync-by-abdulsami.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpmq-5_K9m156WA6GV_SacPuOzoG21eVc',
    appId: '1:778448751554:ios:da2c4b28ae0e553a21e45b',
    messagingSenderId: '778448751554',
    projectId: 'swift-sync-by-abdulsami',
    storageBucket: 'swift-sync-by-abdulsami.firebasestorage.app',
    iosBundleId: 'com.example.uiForProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpmq-5_K9m156WA6GV_SacPuOzoG21eVc',
    appId: '1:778448751554:ios:da2c4b28ae0e553a21e45b',
    messagingSenderId: '778448751554',
    projectId: 'swift-sync-by-abdulsami',
    storageBucket: 'swift-sync-by-abdulsami.firebasestorage.app',
    iosBundleId: 'com.example.uiForProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1wSPjqxyLngjXHT_-eRbeWEhyV_6gck',
    appId: '1:778448751554:web:4653e87c1ed2c53521e45b',
    messagingSenderId: '778448751554',
    projectId: 'swift-sync-by-abdulsami',
    authDomain: 'swift-sync-by-abdulsami.firebaseapp.com',
    storageBucket: 'swift-sync-by-abdulsami.firebasestorage.app',
    measurementId: 'G-F7ZD0MCG1P',
  );
}
